# Generated by Django 5.0.1 on 2024-01-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_image_alter_product_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="aggregate_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
