# Generated by Django 5.0.1 on 2024-01-17 17:13

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_product_image_alter_product_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/product_images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[200, 200],
                upload_to="media/product_thumbnails/",
            ),
        ),
    ]
